# Generated by Django 5.2.5 on 2025-10-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_agent', '0003_content_usercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
