# Generated by Django 5.2.5 on 2025-10-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_agent', '0004_content_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontent',
            name='watch_count',
        ),
    ]
