# Generated by Django 5.2.5 on 2025-11-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_agent', '0005_remove_usercontent_watch_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='liked',
            field=models.BooleanField(null=True),
        ),
    ]
