# Generated by Django 5.2.5 on 2025-11-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_agent', '0006_alter_usercontent_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='justwatchId',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
